import test from 'node:test';
import assert from 'node:assert/strict';
import worker from '../src/worker.mjs';
const valid = {name:'Website test',email:'sender@example.com',topic:'Support',message:'A sample support request for validation.',website:''};
function request(data = valid, headers = {}, options = {}) { return new Request('https://www.casework.work/api/contact',{method:'POST',headers:{Origin:'https://www.casework.work','Content-Type':'application/json',Accept:'application/json','CF-Connecting-IP':'192.0.2.10',...headers},body:JSON.stringify(data),...options}); }
function setup(overrides = {}) { const sent=[]; return {sent,env:{CONTACT_TO:'owner@example.com',EMAIL:{send:async message => {sent.push(message);return {messageId:'test'};}},CONTACT_RATE_LIMITER:{limit:async()=>({success:true})},...overrides}}; }
test('delivers only to the configured inbox, with sender as Reply-To',async()=>{const {env,sent}=setup();const r=await worker.fetch(request({...valid,to:'attacker@example.com'}),env);assert.equal(r.status,200);assert.equal(sent.length,1);assert.equal(sent[0].to,'owner@example.com');assert.equal(sent[0].replyTo,valid.email);assert.equal(sent[0].from.email,'website@casework.work');assert.equal(sent[0].html,undefined);});
test('rejects cross-origin, missing-origin, unsupported and invalid submissions without sending',async()=>{for(const req of [request(valid,{Origin:'https://elsewhere.example'}),request(valid,{Origin:''}),request(valid,{'Content-Type':'text/plain'}),request({...valid,website:'spam'}),request({...valid,email:'bad\r\nBcc: victim@example.com'}),request({...valid,name:'bad\nheader'}),request({...valid,topic:'Unknown'}),request({...valid,message:'short'}),request({...valid,message:'a'.repeat(4001)}),request(null),request([])]){const {env,sent}=setup();const r=await worker.fetch(req,env);assert.ok(r.status>=400);assert.equal(sent.length,0);}});
test('enforces body limit even when content-length is not supplied',async()=>{const {env,sent}=setup();const r=await worker.fetch(request({...valid,message:'a'.repeat(20000)}),env);assert.equal(r.status,413);assert.equal(sent.length,0);});
test('rate limit blocks delivery and gives a retry time',async()=>{const {env,sent}=setup({CONTACT_RATE_LIMITER:{limit:async()=>({success:false})}});const r=await worker.fetch(request(),env);assert.equal(r.status,429);assert.equal(r.headers.get('Retry-After'),'60');assert.equal(sent.length,0);});
test('provider errors never produce success or leak diagnostics',async()=>{const {env}=setup({EMAIL:{send:async()=>{throw Error('private provider diagnostic');}}});const r=await worker.fetch(request(),env);assert.equal(r.status,503);assert.ok(!(await r.text()).includes('private provider'));});
test('missing delivery configuration fails closed',async()=>{const {env}=setup({CONTACT_TO:undefined});const r=await worker.fetch(request(),env);assert.equal(r.status,503);});
test('plain HTML form works without JavaScript',async()=>{const {env,sent}=setup();const req=request(valid,{'Content-Type':'application/x-www-form-urlencoded',Accept:'text/html'},{body:new URLSearchParams(valid)});const r=await worker.fetch(req,env);assert.equal(r.status,200);assert.match(await r.text(),/Message sent/);assert.equal(sent.length,1);});
test('ordinary pages stay on the asset binding; unknown APIs are 404',async()=>{const {env}=setup({ASSETS:{fetch:async()=>new Response('asset')}});assert.equal(await (await worker.fetch(new Request('https://www.casework.work/support'),env)).text(),'asset');assert.equal((await worker.fetch(new Request('https://www.casework.work/api/unknown'),env)).status,404);assert.equal((await worker.fetch(new Request('https://www.casework.work/api/contact'),env)).status,405);});
